In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
%matplotlib qt
import pandas as pd
import math
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
from sociophysicsDataHandler import SociophysicsDataHandler
from libraries.dataManipulation import *

```
guest
YDPGL-XREXC-QGMZS-UAKES
```

In [3]:
# instantiate the storage connection class
dh = SociophysicsDataHandler()
dh.list_files('')

targeting path /storage/surfsara/ProRail_USE_LL_data/
Files listed. Accessible as <this-object>.filelist

,path,name,attributes
0,/storage/surfsara/ProRail_USE_LL_data/asdz/,asdz,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."
1,/storage/surfsara/ProRail_USE_LL_data/config/,config,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."
2,/storage/surfsara/ProRail_USE_LL_data/econophy...,econophysics,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."
3,/storage/surfsara/ProRail_USE_LL_data/ehv/,ehv,"{'{DAV:}getlastmodified': 'Thu, 13 Oct 2022 12..."
4,/storage/surfsara/ProRail_USE_LL_data/sync.sh,sync.sh,"{'{DAV:}getlastmodified': 'Wed, 02 Mar 2022 18..."
5,/storage/surfsara/ProRail_USE_LL_data/upload_l...,upload_log.csv,"{'{DAV:}getlastmodified': 'Wed, 13 Oct 2021 10..."
6,/storage/surfsara/ProRail_USE_LL_data/ut/,ut,"{'{DAV:}getlastmodified': 'Mon, 12 Sep 2022 15..."

In [4]:
dh.fetch_prorail_train_information(station = 'ehv')

trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/ehv_train_information_pss.parquet
data fetched. Accessible as <this-object>.train_information

In [5]:
# let us look at a specific example
day = '20220209'
file_path = 'ehv/platform2.1/' + day

# show all the files in the above directory
# TODO
fLst = dh.list_files(file_path)

targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220209
Files listed. Accessible as <this-object>.filelist

In [6]:
df_train = dh.train_information

#train information grouped by departure time on the platfrom
df_train.head(70)
df_train_per = df_train.groupby('departure_time').first()
df_train_per
df_train_per.iloc[1001:1051]

,date,station,train_number,arrival_time,door_no,door_x,door_y
departure_time,,,,,,,
2022-02-08 06:36:12+01:00,2022-02-08,Ehv,818,2022-02-08 06:33:07+01:00,1,-503.468744,3973.203945
2022-02-08 08:36:10+01:00,2022-02-08,Ehv,826,2022-02-08 08:32:09+01:00,5,56979.100162,3201.625839
2022-02-08 08:58:19+01:00,2022-02-08,Ehv,825,2022-02-08 08:55:22+01:00,3,36077.388759,-9017.814276
2022-02-08 09:26:47+01:00,2022-02-08,Ehv,827,2022-02-08 09:23:55+01:00,5,67464.804540,-9439.121871
2022-02-08 09:36:06+01:00,2022-02-08,Ehv,830,2022-02-08 09:32:05+01:00,5,64470.899838,3101.064770
2022-02-08 09:58:24+01:00,2022-02-08,Ehv,829,2022-02-08 09:55:25+01:00,5,58353.984868,-9316.828989
2022-02-08 10:06:06+01:00,2022-02-08,Ehv,832,2022-02-08 10:02:15+01:00,1,6787.387858,3875.340098
2022-02-08 10:36:07+01:00,2022-02-08,Ehv,834,2022-02-08 10:31:53+01:00,2,4919.114574,3900.417592
2022-02-08 11:06:10+01:00,2022-02-08,Ehv,836,2022-02-08 11:02:54+01:00,1,3187.387858,3923.662246
2022-02-08 11:36:08+01:00,2022-02-08,Ehv,838,2022-02-08 11:32:21+01:00,5,61270.899838,3144.017790
2022-02-08 12:06:16+01:00,2022-02-08,Ehv,840,2022-02-08 12:03:42+01:00,1,13775.790848,3781.536031
2022-02-08 12:36:19+01:00,2022-02-08,Ehv,842,2022-02-08 12:32:24+01:00,5,62770.899838,3123.883562
2022-02-08 13:36:07+01:00,2022-02-08,Ehv,846,2022-02-08 13:31:26+01:00,1,1306.638444,3948.907205
2022-02-08 14:05:59+01:00,2022-02-08,Ehv,848,2022-02-08 14:02:29+01:00,1,-1632.460818,3988.358201
2022-02-08 14:36:11+01:00,2022-02-08,Ehv,850,2022-02-08 14:32:50+01:00,5,68070.899838,3052.742622
2022-02-08 16:36:07+01:00,2022-02-08,Ehv,858,2022-02-08 16:32:02+01:00,1,42.193299,3965.879623
2022-02-08 17:06:07+01:00,2022-02-08,Ehv,860,2022-02-08 17:02:36+01:00,1,3896.531256,3914.143543
2022-02-08 17:36:33+01:00,2022-02-08,Ehv,862,2022-02-08 17:35:18+01:00,1,-1012.612142,3980.038085
2022-02-08 18:54:59+01:00,2022-02-08,Ehv,3779,2022-02-08 18:51:26+01:00,4,37606.638444,3461.658882
2022-02-08 19:30:43+01:00,2022-02-08,Ehv,867,2022-02-08 19:25:22+01:00,5,64070.899838,-9393.566103
2022-02-08 19:57:36+01:00,2022-02-08,Ehv,869,2022-02-08 19:54:32+01:00,1,2462.236534,-8566.604179
2022-02-08 20:04:18+01:00,2022-02-08,Ehv,2972,2022-02-08 20:01:50+01:00,2,6189.072239,3883.371180
2022-02-08 20:34:31+01:00,2022-02-08,Ehv,2974,2022-02-08 20:32:49+01:00,5,55674.209152,3219.141155
2022-02-09 06:59:54+01:00,2022-02-09,Ehv,2917,2022-02-09 06:58:27+01:00,1,15955.747613,-8747.725133
2022-02-09 08:36:15+01:00,2022-02-09,Ehv,826,2022-02-09 08:32:38+01:00,5,63484.847775,3114.300368
2022-02-09 09:05:58+01:00,2022-02-09,Ehv,828,2022-02-09 09:04:15+01:00,5,67270.899838,3063.480877
2022-02-09 09:28:33+01:00,2022-02-09,Ehv,827,2022-02-09 09:26:06+01:00,4,49553.984868,-9198.708184
2022-02-09 09:36:02+01:00,2022-02-09,Ehv,830,2022-02-09 09:32:22+01:00,3,24179.100162,3641.894296
2022-02-09 10:00:17+01:00,2022-02-09,Ehv,829,2022-02-09 09:57:49+01:00,5,56789.072239,-9295.823450
2022-02-09 10:06:03+01:00,2022-02-09,Ehv,832,2022-02-09 10:03:31+01:00,6,66601.711403,3072.463272
2022-02-09 10:36:05+01:00,2022-02-09,Ehv,834,2022-02-09 10:33:59+01:00,1,-1632.460818,3988.358201
2022-02-09 11:07:27+01:00,2022-02-09,Ehv,836,2022-02-09 11:05:58+01:00,5,61270.899838,3144.017790
2022-02-09 11:36:06+01:00,2022-02-09,Ehv,838,2022-02-09 11:34:33+01:00,1,-1632.460818,3988.358201
2022-02-09 12:05:58+01:00,2022-02-09,Ehv,840,2022-02-09 12:02:21+01:00,5,53072.611241,3254.061932
2022-02-09 12:36:13+01:00,2022-02-09,Ehv,842,2022-02-09 12:32:20+01:00,1,12087.387858,3804.199159
2022-02-09 13:07:09+01:00,2022-02-09,Ehv,844,2022-02-09 13:05:42+01:00,6,72000.000000,3000.003023
2022-02-09 13:36:02+01:00,2022-02-09,Ehv,846,2022-02-09 13:31:58+01:00,1,687.387858,3957.219293
2022-02-09 14:05:52+01:00,2022-02-09,Ehv,848,2022-02-09 14:01:57+01:00,1,7175.790848,3870.126635
2022-02-09 14:36:08+01:00,2022-02-09,Ehv,850,2022-02-09 14:32:15+01:00,4,42272.611241,3399.028375
2022-02-09 15:11:56+01:00,2022-02-09,Ehv,852,2022-02-09 15:08:13+01:00,1,-1812.612142,3990.776340
2022-02-09 15:36:05+01:00,2022-02-09,Ehv,854,2022-02-09 15:32:15+01:00,5,63770.899838,3110.460743
2022-02-09 16:36:13+01:00,2022-02-09,Ehv,858,2022-02-09 16:34:05+01:00,1,17242.193299,3735.007139
2022-02-09 17:06:07+01:00,2022-02-09,Ehv,860,2022-02-09 17:04:38+01:00,5,55201.711403,3225.483406
2022-02-09 17:36:16+01:00,2022-02-09,Ehv,862,2022-02-09 17:33:05+01:00,1,11555.747613,3811.335269
2022-02-09 18:07:27+01:00,2022-02-09,Ehv,864,2022-02-09 18:01:56+01:00,4,42272.611241,3399.028375
2022-02-09 18:28:13+01:00,2022-02-09,Ehv,863,2022-02-09 18:24:59+01:00,3,25279.100162,-8872.870805
2022-02-09 19:02:59+01:00,2022-02-09,Ehv,865,2022-02-09 18:58:57+01:00,5,53584.594668,-9252.810329
2022-02-09 19:27:07+01:00,2022-02-09,Ehv,867,2022-02-09 19:24:46+01:00,1,2009.709962,-8560.529997
2022-02-10 08:36:06+01:00,2022-02-10,Ehv,826,2022-02-10 08:32:04+01:00,2,8516.682580,3852.128089
2022-02-10 08:57:21+01:00,2022-02-10,Ehv,3928,2022-02-10 08:50:24+01:00,3,33894.846874,-8988.518412

In [7]:
df_train_per[df_train_per['train_number'] == '826']

,date,station,train_number,arrival_time,door_no,door_x,door_y
departure_time,,,,,,,
2022-01-03 08:36:00+01:00,2022-01-03,Ehv,826,2022-01-03 08:33:51+01:00,4,45233.317420,3359.287353
2022-01-04 08:36:02+01:00,2022-01-04,Ehv,826,2022-01-04 08:33:20+01:00,1,15775.790848,3754.690394
2022-01-05 08:36:07+01:00,2022-01-05,Ehv,826,2022-01-05 08:32:00+01:00,2,19694.846874,3702.085615
2022-01-06 08:36:02+01:00,2022-01-06,Ehv,826,2022-01-06 08:32:00+01:00,5,53072.611241,3254.061932
2022-01-07 08:36:05+01:00,2022-01-07,Ehv,826,2022-01-07 08:32:08+01:00,4,45774.209152,3352.027061
...,...,...,...,...,...,...,...
2022-09-23 08:38:22+02:00,2022-09-23,Ehv,826,2022-09-23 08:35:33+02:00,2,24345.108989,3639.665989
2022-09-24 08:38:06+02:00,2022-09-24,Ehv,826,2022-09-24 08:36:16+02:00,2,14065.152225,3777.651986
2022-09-26 08:36:04+02:00,2022-09-26,Ehv,826,2022-09-26 08:32:32+02:00,3,30862.236534,3552.187767
2022-09-27 08:36:13+02:00,2022-09-27,Ehv,826,2022-09-27 08:32:05+02:00,1,-822.611241,3977.487737
2022-09-28 08:36:07+02:00,2022-09-28,Ehv,826,2022-09-28 08:32:44+02:00,2,8406.638444,3853.605191

In [8]:
def checkBounds(df, limits, x_tag = 'x_pos', y_tag = 'y_pos'):
  x_lower = limits[0]
  x_upper = limits[1]
  y_lower = limits[2]
  y_upper = limits[3]

  within_xbounds_series = (df[x_tag] < x_upper) & (df[x_tag] > x_lower)
  within_ybounds_series = (df[y_tag] < y_upper) & (df[y_tag] > y_lower)
  within_bounds_series = within_xbounds_series & within_ybounds_series
  return within_bounds_series

In [9]:
def checkZones(df, zone_names, limits_array):
    for i in range(len(zone_names)):
        df[zone_names[i]] = checkBounds(df, limits_array[i]).astype(float)
    return df

In [10]:
#Function to generate a dataframe with the number of people leaving and entering each zone
def calculate_flux(dataframe, sampling_period):
    
    #Initiate flux dictionaries
    entered_set = {}
    left_set = {}

    t_i = math.floor(dataframe['date_time_utc'].iloc[0].timestamp()) 
    t_i = math.floor(t_i/sampling_period) * sampling_period #Round the time to the nearest sampling period multiple
    t_f = math.floor(dataframe['date_time_utc'].iloc[len(dataframe)-1].timestamp())
    t_f = math.floor(t_f/sampling_period) * sampling_period #Round the time to the nearest sampling period multiple

    # Loop through every second in considered dataframe
    for t in range(t_i, t_f+1, sampling_period):
        entered_set[t] = {}
        left_set[t] = {}
        #Loop through every zone and set the default value to zero
        for zone_name in zone_names:
            entered_set[t][zone_name] = 0
            left_set[t][zone_name] = 0
    
    #Loop through all the IDs in the dataframe
    df_grouped_by_id = dataframe.groupby('tracked_object')
    for index, df_id in df_grouped_by_id:
        #Shift and overlay the boolean values for the zone to detect when a person switches zone   
        #If there is a difference between the previous zone (shifted value) and current zone, a person has changed zone
        df_shifted = df_id[zone_names].shift(periods = -1)
        df_overlay = (df_id[zone_names] != df_shifted)

        #If the shifted and non shifted dataframe don't match, two values will differ (zone left and zone entered)
        #Thus the sum of that specific row will be 2, because True values are returned for differences (!= is used)
        df_id['changed'] = df_overlay.sum(axis=1) == 2
        df_left = df_id[df_id['changed']]
        df_entered = df_id[df_id['changed'].shift(periods= 1) | False]

        #Extract the information from the zone transitions and put them in the dictionary left_set and entered_set  
        zones_left = df_left[zone_names].idxmax(axis = 1)
        for i in range(zones_left.size):
            time = (df_left['date_time_utc'].iloc[i].timestamp())
            time = math.floor(time/sampling_period)*sampling_period #Round the time to the nearest sampling period multiple
            left_set[time][zones_left.iloc[i]] -= 1

        zones_entered = df_entered[zone_names].idxmax(axis = 1)
        for i in range(zones_entered.size):
            time = math.floor(df_entered['date_time_utc'].iloc[i].timestamp())
            time = math.floor(time/sampling_period)*sampling_period #Round the time to the nearest sampling period multiple
            entered_set[time][zones_entered.iloc[i]] += 1

    #Convert the dictionary of people that left or entered a zone to a dataframe
    df_entered_set = pd.DataFrame.from_dict(entered_set)
    df_entered = df_entered_set.transpose()
    df_left_set = pd.DataFrame.from_dict(left_set)
    df_left = df_left_set.transpose()

    #Changing the index from datetime to time in seconds from start
    time = list(range(0,len(df_entered)*sampling_period, sampling_period))
    df_time = pd.DataFrame (time, columns = ['time(s)'])

    df_entered = df_entered.reset_index()
    df_entered = df_entered.drop("index", axis=1)
    df_left = df_left.reset_index()
    df_left = df_left.drop("index", axis=1)
    

    df_entered = pd.concat([df_time, df_entered], axis=1)    
    df_left = pd.concat([df_time, df_left], axis=1)
    
    #Combine both to get the net flux
    df_net = df_entered + df_left
    df_net['time(s)'] = df_entered['time(s)']

    return df_entered, df_left, df_net

In [11]:
#Calculating the density
def calculate_density(df_density, sampling_period):

    #Sum the number of people in each zone for every moment in time
    df_totals = df_density.groupby('date_time_utc').sum().drop(columns=['tracked_object', 'y_pos', 'x_pos'])
    #Take the average number of people in a zone during each sampling period
    df_totals = df_totals.resample(str(sampling_period) + 'S').mean()
    

    def area_of_limits(limits):
      return abs((limits[0]-limits[1])*(limits[2]-limits[3]))

    for i in range(len(dens_names)):
        df_totals[dens_names[i]] = df_totals[zone_names[i]] / area_of_limits(limits_array[i])

    
    time = list(range(0,len(df_totals)*sampling_period, sampling_period))
    df_time = pd.DataFrame (time, columns = ['time(s)'])

    df_totals = df_totals.reset_index()
    df_totals = df_totals.drop('date_time_utc', axis=1)
    
    df_totals = pd.concat([df_time, df_totals], axis=1)


    return df_totals

In [12]:
#Define variables needed for determining the inflow and outflow of certain areas

#Limits of the boarding area on the upper side (1) and lower side (2) of the platform in Eindhoven
bot_lim = -8.3e3
top_lim = 2.4e3
boarding_limits_E_O = [-5e3, 5e3, -5e2, 1.5e3] #x_lower, x_upper, y_lower, y_upper
boarding_limits_STAIRS = [-5e3, 5e3, -4.5e3, -5e2]
boarding_limits_E_I = [-5e3, 5e3, -6.5e3, -4.5e3]
boarding_limits_1_1 = [5e3, 1e4, -2.5e3, top_lim] 
boarding_limits_1_2 = [5e3, 1e4, bot_lim, -2.5e3]
boarding_limits_2_1 = [1e4, 2.8e4, -2.5e3, top_lim]
boarding_limits_2_2 = [1e4, 2.8e4, bot_lim, -2.5e3]
boarding_limits_3_1 = [2.8e4, 5e4, -2.5e3, top_lim]
boarding_limits_3_2 = [2.8e4, 5e4, bot_lim, -2.5e3]
boarding_limits_4_1 = [5e4, 7.5e4, -3e3, top_lim]
boarding_limits_4_2 = [5e4, 7.5e4, bot_lim, -3e3]
boarding_limits_danger_1_1 = [-5e3, 1e4, top_lim, 4.5e3]
boarding_limits_danger_1_2 = [-5e3, 1e4, -1e4, bot_lim]
boarding_limits_danger_2_1 = [1e4, 2.8e4, top_lim, 4.5e3]
boarding_limits_danger_2_2 = [1e4, 2.8e4, -1e4, bot_lim]
boarding_limits_danger_3_1 = [2.8e4, 5e4, top_lim, 4.5e3]
boarding_limits_danger_3_2 = [2.8e4, 5e4, -1e4, bot_lim]
boarding_limits_danger_4_1 = [5e4, 7.5e4, top_lim, 4.5e3]
boarding_limits_danger_4_2 = [5e4, 7.5e4, -1e4, bot_lim]

limits_array = [boarding_limits_E_O, boarding_limits_STAIRS ,boarding_limits_E_I ,boarding_limits_1_1,boarding_limits_1_2 ,
boarding_limits_2_1,boarding_limits_2_2 ,boarding_limits_3_1,boarding_limits_3_2 ,boarding_limits_4_1 ,boarding_limits_4_2 ,
boarding_limits_danger_1_1 ,boarding_limits_danger_1_2 ,boarding_limits_danger_2_1,boarding_limits_danger_2_2 ,
boarding_limits_danger_3_1 ,boarding_limits_danger_3_2 ,boarding_limits_danger_4_1 ,boarding_limits_danger_4_2]

#Name as a string of the boundaries defined above
zone_names = ['E_O', 'STAIRS','E_I', '1.1', '1.2', '2.1', '2.2', '3.1', '3.2', '4.1', '4.2', 
              'danger_1_1', 'danger_1_2','danger_2_1', 'danger_2_2','danger_3_1', 'danger_3_2', 'danger_4_1', 'danger_4_2']
zone_names_array =  [['E_O','danger_1_1','danger_2_1','danger_3_1', 'danger_4_1'],
                     ['STAIRS','1.1','2.1', '3.1','4.1'], 
                     ['STAIRS' , '1.2',  '2.2', '3.2' , '4.2'],
                     ['E_I', 'danger_1_2', 'danger_2_2', 'danger_3_2',  'danger_4_2']]

#Names for the density plots
dens_names = ['density_E_O','density_STAIRS','density_E_I','density_1_1','density_1_2','density_2_1', 'density_2_2',
              'density_3_1','density_3_2','density_4_1','density_4_2','density_danger_1_1','density_danger_1_2',
              'density_danger_2_1', 'density_danger_2_2', 'density_danger_3_1', 'density_danger_3_2', 'density_danger_4_1',
              'density_danger_4_2']

dens_names_array = [['density_E_O','density_danger_1_1','density_danger_2_1','density_danger_3_1', 'density_danger_4_1'],
                     ['density_STAIRS','density_1_1','density_2_1', 'density_3_1','density_4_1'], 
                     ['density_STAIRS' , 'density_1_2',  'density_2_2', 'density_3_2' , 'density_4_2'],
                     ['density_E_I', 'density_danger_1_2', 'density_danger_2_2', 'density_danger_3_2',  'density_danger_4_2']]

In [13]:
#Selected times to look at
#Morning rush hour a lot of people leave the train in Eindhoven
begin_times = [pd.to_datetime('2022-02-04 07:31:00.000'),pd.to_datetime('2022-02-05 07:31:00.000'), pd.to_datetime('2022-02-07 07:31:00.000'),pd.to_datetime('2022-02-08 07:31:00.000'),pd.to_datetime('2022-02-09 07:31:00.000'), pd.to_datetime('2022-02-10 07:31:00.000')]
end_times = [pd.to_datetime('2022-02-04 07:36:00.000'), pd.to_datetime('2022-02-05 07:36:00.000'), pd.to_datetime('2022-02-07 07:36:00.000'), pd.to_datetime('2022-02-08 07:36:00.000'), pd.to_datetime('2022-02-09 07:36:00.000'), pd.to_datetime('2022-02-10 07:36:00.000')]

#Set a sampling period to add up the outflow and inflow within the same period
sampling_period = 10 #Sampling period in seconds

In [14]:
#For every timesecion defined before, calculate flux and density and take the average

for i in range(len(begin_times)):
    begin_time = begin_times[i]
    end_time = end_times[i]
    df_i = getTime(begin_time,end_time, 'ehv')
    
    #Check in which zones everyone is
    df_i = checkZones(df_i, zone_names, limits_array)
    
    #Calculate flux and density
    df_entered_i, df_left_i, df_net_i = calculate_flux(df_i, sampling_period)
    df_density_i = calculate_density(df_i, sampling_period)
    if (i == 0):
        df_entered = df_entered_i
        df_left = df_left_i
        df_net = df_net_i
        df_density = df_density_i
    else:
        df_entered = df_entered + df_entered_i
        df_left = df_left + df_left_i
        df_net = df_net + df_net_i
        df_density = df_density + df_density_i

df_entered = df_entered / (i+1)
df_left = df_left / (i+1)
df_net = df_net / (i+1)
df_density = df_density / (i+1)
df = df_i

targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220204
Files listed. Accessible as <this-object>.filelist
trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220204/EHV_Platform2.1_2022020408_trajectorie.parquet
data fetched. Accessible as <this-object>.df
targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220205
Files listed. Accessible as <this-object>.filelist
trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220205/EHV_Platform2.1_2022020508_trajectorie.parquet
data fetched. Accessible as <this-object>.df
targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220207
Files listed. Accessible as <this-object>.filelist
trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220207/EHV_Platform2.1_2022020708_trajectorie.parquet
data fetched. Accessible as <this-object>.df
targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220208
Files listed. Accessible as <this-object>.filelist
trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220208/EHV_Platform2.1_2022020808_trajectorie.parquet
data fetched. Accessible as <this-object>.df
targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220209
Files listed. Accessible as <this-object>.filelist
trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220209/EHV_Platform2.1_2022020908_trajectorie.parquet
data fetched. Accessible as <this-object>.df
targeting path /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220210
Files listed. Accessible as <this-object>.filelist
trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/platform2.1/20220210/EHV_Platform2.1_2022021008_trajectorie.parquet
data fetched. Accessible as <this-object>.df

In [15]:
#Working out the net flux: entered-left

df_flux_sum = df_net.sum().to_frame()
df_flux_sum = df_flux_sum.rename(columns = {0:'sum'})
df_flux_sum

                    sum
time(s)     4650.000000
E_O          101.666667
STAIRS       144.333333
E_I          -35.500000
1.1           -9.333333
1.2            1.833333
2.1          -30.166667
2.2           -1.333333
3.1          -24.666667
3.2            2.500000
4.1          -96.833333
4.2          -25.500000
danger_1_1     3.833333
danger_1_2     1.833333
danger_2_1     1.333333
danger_2_2     0.500000
danger_3_1   -17.166667
danger_3_2     0.000000
danger_4_1   -17.666667
danger_4_2     0.333333

In [16]:
df_flux_sum = df_flux_sum.drop(index='time(s)')
df_flux_sum.plot.bar()

In [17]:
#working out the sum of flux on each region

 #maybe automate this in case we increase the number of zones

sums =  []



for k in range(0, len(zone_names)):
    sums.append((df_net[zone_names[k]].sum()))



df_sums = pd.DataFrame(sums)
df_zones = pd.DataFrame(zone_names)

df_sums = pd.concat([ df_zones, df_sums], axis=1)
df_sums

#df_Sums = df_sums.set_axis(['zones', 'flux sum'], axis='columns', inplace=True)

#df_Sums

             0           0
0          E_O  101.666667
1       STAIRS  144.333333
2          E_I  -35.500000
3          1.1   -9.333333
4          1.2    1.833333
5          2.1  -30.166667
6          2.2   -1.333333
7          3.1  -24.666667
8          3.2    2.500000
9          4.1  -96.833333
10         4.2  -25.500000
11  danger_1_1    3.833333
12  danger_1_2    1.833333
13  danger_2_1    1.333333
14  danger_2_2    0.500000
15  danger_3_1  -17.166667
16  danger_3_2    0.000000
17  danger_4_1  -17.666667
18  danger_4_2    0.333333

In [18]:
df_sums.sum()

0    E_OSTAIRSE_I1.11.22.12.23.13.24.14.2danger_1_1...
0                                                  0.0
dtype: object

In [31]:
#plotting the net flux and density
df_density_scaled = df_density.copy()
df_density_scaled[dens_names] = df_density_scaled[dens_names] * 1e7
previous_ax2 = 0

rows = len(zone_names_array)
cols = len(zone_names_array[0])
fig, ax = plt.subplots(rows,cols, figsize = (30,20), sharey = True, sharex = True)

for i in range(rows):
    for j in range(cols):
        ax1 = ax[i,j]
        ax2 = ax1.twinx()
        if previous_ax2 != 0:
            ax2.get_shared_y_axes().join(ax2,previous_ax2)
        df_net.plot('time(s)', zone_names_array[i][j], ax = ax1, linewidth = 1.5, legend = None)
        df_density_scaled.plot('time(s)', dens_names_array[i][j], ax = ax2, c = 'orange', linewidth = 1.5, legend = None)
        
        ax1.set_title(zone_names_array[i][j], size = 14)
        ax1.grid(True)
        ax1.set_xlabel('Time ($s$)', size = 12)
        
        if (i == 0 and j == 0):
            ax1.set_ylabel('Flux ($\cdot 10^{-1} people/s$)', size = 12)
            ax2.set_ylabel('Density ($\cdot 10^{-1} people/m^2$)', size = 12)
    
        previous_ax2 = ax2

        
handles, labels = [(a + b) for a, b in zip(ax1.get_legend_handles_labels(), ax2.get_legend_handles_labels())]
fig.legend(handles, ('Flux', 'Density'), loc='upper right', bbox_to_anchor = (0.95,0.95))
fig.suptitle('Density and net flux over time at train arrival for different zones', size = 18, weight = 'bold')

Text(0.5, 0.98, 'Density and net flux over time at train arrival for different zones')

In [20]:
# Plotting each flux for entered and left
rows = len(zone_names_array)
cols = len(zone_names_array[0])
fig, ax = plt.subplots(rows,cols, figsize = (30,20), sharey = True, sharex = True)
for i in range(rows):
    for j in range(cols):
        df_left.plot('time(s)', zone_names_array[i][j], ax = ax[i,j], linewidth = 0.5)
        df_entered.plot('time(s)', zone_names_array[i][j], ax = ax[i,j], linewidth = 0.5)
        ax[i,j].set_title(zone_names_array[i][j])
        ax[i,j].legend(['left', 'entered'])
        ax[i,j].grid('on')

In [21]:
##Normalsing the density

#dropping columns to make sets of which they are normalised amongst
df_density_nor = df_density.drop(df_density.loc[:, 'time(s)':'danger_4_2'].columns,axis = 1)
df_density_nor

#Normalising amongst the density columns
normalized_df_density = (df_density_nor-df_density_nor.min().min())/(df_density_nor.max().max()-df_density_nor.min().min())
normalized_df_density

df_density_conc = df_density.drop(df_density.loc[:, 'density_E_O':'density_danger_4_2'].columns,axis = 1)
df_density_conc

#Concatenating the new normalised dataframe 
df_density_normalised = pd.concat([df_density_conc, normalized_df_density], axis=1)
df_density_normalised

,time(s),E_O,STAIRS,E_I,1.1,1.2,2.1,2.2,3.1,3.2,...,density_4_1,density_4_2,density_danger_1_1,density_danger_1_2,density_danger_2_1,density_danger_2_2,density_danger_3_1,density_danger_3_2,density_danger_4_1,density_danger_4_2
0,0.0,2.408333,0.255000,0.811667,4.258333,1.570000,16.058333,2.363333,10.291667,0.943333,...,0.128138,0.026536,0.009291,0.000000,0.002751,0.000503,0.000000,0.000000,0.003301,0.000000
1,10.0,2.701667,0.025000,1.095000,4.353333,1.796667,16.481667,2.483333,10.485000,0.723333,...,0.142258,0.032668,0.004279,0.000000,0.009882,0.000000,0.000000,0.000000,0.000000,0.000000
2,20.0,2.970000,0.101667,1.133333,4.408333,1.920000,17.373333,3.365000,10.608333,0.361667,...,0.150873,0.034499,0.005868,0.000000,0.005705,0.000000,0.003834,0.000000,0.000000,0.000000
3,30.0,3.008333,0.088333,0.715000,4.908333,1.615000,18.876667,3.890000,10.633333,0.303333,...,0.155865,0.029703,0.000000,0.002265,0.000000,0.000000,0.008669,0.000000,0.000000,0.000000
4,40.0,2.548333,0.063333,0.526667,4.778333,1.531667,19.138333,3.318333,10.863333,0.986667,...,0.156122,0.023542,0.004279,0.002114,0.000204,0.000503,0.000000,0.001133,0.000000,0.000000
5,50.0,2.198333,0.055000,1.121667,4.620000,1.330000,19.973333,2.506667,10.695000,1.368333,...,0.164537,0.018601,0.049757,0.002416,0.008660,0.000000,0.006502,0.007929,0.000000,0.000000
6,60.0,0.725000,0.166667,0.618333,4.773333,1.515000,18.966667,2.571667,10.590000,0.990000,...,0.166534,0.023280,0.139247,0.000906,0.057969,0.000000,0.035009,0.005045,0.012763,0.004078
7,70.0,1.028333,0.830000,0.783333,5.521667,0.951667,20.528333,2.001667,14.731667,0.771667,...,0.241956,0.049816,0.248542,0.000000,0.093422,0.000000,0.090940,0.003604,0.037483,0.000000
8,80.0,3.236667,2.368333,0.915000,7.850000,1.603333,24.060000,1.986667,21.403333,2.095000,...,0.321658,0.072486,0.240228,0.003775,0.098109,0.000000,0.150039,0.002162,0.033815,0.000000
9,90.0,4.770000,4.255000,0.725000,7.573333,2.441667,24.425000,2.576667,24.688333,4.118333,...,0.380592,0.079810,0.283751,0.000000,0.140592,0.000000,0.153456,0.000000,0.030074,0.001178
10,100.0,5.070000,4.331667,0.558333,8.863333,1.408333,19.896667,4.035000,26.718333,5.238333,...,0.458011,0.102683,0.257955,0.000000,0.149964,0.000000,0.182130,0.002677,0.039757,0.000000
11,110.0,6.501667,7.886667,0.570000,8.143333,1.841667,18.698333,5.040000,30.641667,6.370000,...,0.553715,0.139188,0.187782,0.000000,0.145482,0.000000,0.174628,0.005148,0.041371,0.004712
12,120.0,6.861667,7.940000,0.491667,6.485000,1.440000,21.146667,5.555000,33.941667,7.963333,...,0.541364,0.172147,0.106483,0.000000,0.135396,0.000000,0.182630,0.003707,0.036016,0.002809
13,130.0,5.560000,6.695000,0.958333,7.165000,1.746667,22.505000,6.776667,39.978333,9.263333,...,0.437216,0.211151,0.025307,0.000000,0.080586,0.000000,0.188298,0.000000,0.025600,0.007068
14,140.0,6.366667,7.960000,0.605000,7.448333,2.381667,23.093333,8.121667,36.845000,11.080000,...,0.339172,0.207227,0.009658,0.003171,0.044724,0.000000,0.159458,0.007826,0.013644,0.008880
15,150.0,6.078333,7.521667,0.520000,9.013333,2.896667,23.788333,9.918333,31.865000,11.015000,...,0.240929,0.178889,0.048535,0.000000,0.050124,0.000000,0.157874,0.006693,0.012983,0.015042
16,160.0,6.780000,10.525000,0.653333,9.676667,3.676667,24.510000,10.278333,25.241667,9.811667,...,0.189526,0.119308,0.006479,0.000000,0.091996,0.000000,0.101526,0.011841,0.018411,0.004893
17,170.0,7.108333,12.685000,0.858333,10.603333,3.501667,23.033333,8.835000,17.778333,7.613333,...,0.173066,0.105474,0.031419,0.000604,0.045743,0.000000,0.045928,0.003810,0.022739,0.005890
18,180.0,7.011667,10.588333,0.578333,10.193333,3.130000,20.985000,8.746667,11.098333,5.491667,...,0.148220,0.078240,0.018827,0.000000,0.053486,0.000000,0.036676,0.000000,0.009169,0.000816
19,190.0,6.908333,10.130341,0.477851,9.220000,2.796707,16.540000,5.980000,7.733333,4.968333,...,0.105202,0.046532,0.012062,0.000906,0.051347,0.000000,0.023839,0.000103,0.005648,0.009333
20,200.0,5.931667,8.985000,0.440000,6.633333,2.331667,9.683333,5.401667,7.086667,2.776667,...,0.057822,0.026274,0.005624,0.000000,0.005501,0.000000,0.019338,0.000000,0.006822,0.000634
21,210.0,4.716667,6.070000,0.245000,4.755000,1.218333,7.413333,3.630000,3.581667,1.748333,...,0.041762,0.012062,0.011492,0.007702,0.004585,0.000378,0.016588,0.000000,0.007189,0.000000
22,220.0,3.681667,4.210000,0.471667,2.793333,0.798333,5.083333,2.436667,1.555000,0.486667,...,0.019597,0.010463,0.005257,0.000000,0.011410,0.000000,0.004501,0.000000,0.009829,0.000000
23,230.0,1.956667,2.210000,0.365000,1.543333,0.605000,2.556667,1.663333,1.206667,0.000000,...,0.008672,0.009620,0.013203,0.000000,0.000306,0.000000,0.000000,0.000000,0.005942,0.000000
24,240.0,0.774192,0.508333,0.516667,0.852290,0.241667,1.410185,1.063333,0.995000,0.000000,...,0.010612,0.008719,0.012225,0.000000,0.000815,0.000000,0.001250,0.000000,0.006895,0.000000
25,250.0,0.480000,0.128333,0.627549,0.301667,0.372059,2.100000,1.002059,0.121667,0.145000,...,0.009784,0.009998,0.005379,0.000000,0.001936,0.000000,0.000000,0.000000,0.008289,0.000000
26,260.0,0.266667,0.025000,0.508333,0.295000,0.406667,1.806667,1.268333,0.150000,0.198333,...,0.011439,0.009359,0.005990,0.000000,0.000000,0.000000,0.005418,0.000000,0.008656,0.000000
27,270.0,0.488333,0.010000,0.286667,0.466667,0.096667,1.028333,1.498333,0.171667,0.438333,...,0.012238,0.008719,0.001589,0.000000,0.000000,0.000000,0.000000,0.000000,0.008215,0.000000
28,280.0,0.236667,0.003333,0.266667,0.003333,0.171667,1.058333,1.226667,0.000000,0.571667,...,0.013150,0.011015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004034,0.000000
29,290.0,0.000000,0.000000,0.196667,0.000000,0.061667,0.910000,1.256667,0.173333,0.666667,...,0.010412,0.012091,0.000000,0.000000,0.001732,0.000000,0.000000,0.000000,0.003374,0.000000
30,300.0,0.000000,0.000000,0.333333,0.000000,0.000000,1.000000,1.333333,0.333333,0.666667,...,0.008558,0.011626,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [22]:
#Plotting the density
rows = len(dens_names_array)
cols = len(dens_names_array[0])
fig, ax = plt.subplots(rows,cols, figsize = (30,20), sharex = True, sharey = True)
for i in range(rows):
    for j in range(cols):
        df_density_normalised[['time(s)', dens_names_array[i][j]]].plot('time(s)',ax = ax[i,j], linewidth = 0.5, x_compat=True)
            
        ax[i,j].set_title("Density " + zone_names_array[i][j])
        ax[i,j].grid('on')

In [23]:
df_net.tail(5)

,time(s),E_O,STAIRS,E_I,1.1,1.2,2.1,2.2,3.1,3.2,4.1,4.2,danger_1_1,danger_1_2,danger_2_1,danger_2_2,danger_3_1,danger_3_2,danger_4_1,danger_4_2
26,260.0,0.333333,0.0,-1.166667,0.333333,0.166667,-0.333333,0.000000,0.333333,0.166667,0.000000,0.000000,0.500000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
27,270.0,0.833333,0.0,-0.333333,-0.333333,-0.333333,-0.833333,0.333333,0.000000,0.166667,0.333333,0.000000,0.333333,0.0,0.000000,0.0,0.0,0.0,-0.333333,0.0
28,280.0,0.000000,0.0,-0.166667,0.000000,0.000000,0.166667,-0.333333,0.000000,0.166667,0.000000,0.166667,0.000000,0.0,0.000000,0.0,0.0,0.0,0.166667,0.0
29,290.0,0.000000,0.0,-0.166667,0.000000,0.000000,-0.166667,0.166667,0.166667,0.000000,-0.333333,0.000000,0.000000,0.0,0.166667,0.0,0.0,0.0,0.166667,0.0
30,300.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0

In [24]:
df_flux_over_density = df_net/df_density_normalised
df_flux_over_density

,1.1,1.2,2.1,2.2,3.1,3.2,4.1,4.2,E_I,E_O,...,density_STAIRS,density_danger_1_1,density_danger_1_2,density_danger_2_1,density_danger_2_2,density_danger_3_1,density_danger_3_2,density_danger_4_1,density_danger_4_2,time(s)
0,0.078278,0.000000,-0.010379,-0.141044,0.048583,0.353357,0.089047,0.109529,-1.232033,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.114855,0.185529,0.010112,0.067114,0.000000,-0.691244,0.080209,0.177936,-1.522070,0.061690,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,0.226843,-0.173611,0.047966,0.198118,0.000000,-0.460829,0.037814,0.084246,-1.764706,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,0.033956,-0.206398,0.017658,0.085690,0.000000,0.000000,0.073206,-0.097847,-1.398601,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,-0.069759,-0.326442,0.026126,-0.502260,0.092053,1.013514,0.000000,0.000000,-1.898734,0.065402,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,-0.072150,0.501253,-0.008344,0.066489,-0.109085,-0.243605,0.138696,0.000000,-1.634473,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
6,0.139665,0.000000,-0.070299,-0.324044,0.157381,0.000000,0.205550,0.499376,-2.425876,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
7,-0.181105,0.175131,0.073070,-0.083264,0.305464,0.647948,0.153266,0.641774,-1.489362,2.593193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
8,-0.233546,0.311850,0.062344,-0.251678,0.093443,0.954654,-0.124158,0.080192,-2.003643,1.596292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9,-0.506162,-0.341297,-0.102354,0.452781,0.013502,0.283286,-0.352271,0.000000,-2.528736,1.048218,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
10,0.150432,0.000000,-0.293181,0.578273,0.187137,0.381801,-0.186846,0.000000,-1.791045,1.249178,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
11,-0.307000,0.180995,-0.106961,0.066138,0.152298,0.078493,-0.324558,-0.104406,-1.754386,1.204819,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
12,0.000000,-0.578704,0.031526,0.210021,0.039283,0.251151,-0.558541,0.033767,-2.033898,1.093029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
13,-0.116306,0.954198,0.081463,0.122971,-0.100054,0.179921,-0.639395,-0.206469,-1.739130,1.258993,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
14,0.179011,-0.419874,-0.028868,0.246255,-0.167368,0.210590,-0.672834,-0.392707,-2.203857,1.099476,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
15,0.184911,0.402762,-0.021019,0.184843,-0.209216,-0.136178,-0.615676,-0.617384,-1.923077,1.179051,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
16,0.344471,0.634633,-0.088399,-0.162153,-0.277319,-0.169866,-0.602047,-0.755177,-2.040816,1.032448,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
17,0.031437,-0.190386,-0.065123,0.000000,-0.440611,-0.262697,-0.494478,-0.606228,-1.941748,0.867526,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
18,-0.098103,-0.053248,-0.127075,-0.114329,-0.465535,-0.212443,-0.442648,-0.705795,-2.881844,1.188495,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
19,-0.072307,0.059594,-0.342604,-0.362319,-0.172414,-0.369004,-0.732114,-0.624610,-2.441484,0.747889,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
20,-0.201005,0.071480,-0.722892,-0.030855,-0.258702,-0.300120,-0.296004,-0.995575,-1.893939,0.927227,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
21,-0.525762,-1.231190,-0.067446,-0.550964,-0.884132,-0.476644,-0.478142,0.240964,-1.360544,0.989399,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
22,-0.596659,0.835073,-0.459016,-0.547196,-0.214362,-1.712329,-1.018923,0.000000,-2.826855,0.995926,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
23,-1.187905,-0.550964,-0.391134,-0.400802,-0.414365,NaN,0.328947,0.000000,-2.739726,1.362862,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
24,0.195552,0.000000,-0.709127,0.000000,-0.335008,NaN,0.000000,0.000000,-2.258065,0.861113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
25,-1.657459,0.895916,0.317460,0.000000,-5.479452,1.149425,0.291545,0.000000,-2.124668,1.388889,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
26,1.129944,0.409836,-0.184502,0.000000,2.222222,0.840336,0.000000,0.000000,-2.295082,1.250000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
27,-0.714286,-3.448276,-0.810373,0.222469,0.000000,0.380228,0.466200,0.000000,-1.162791,1.706485,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
28,0.000000,0.000000,0.157480,-0.271739,NaN,0.291545,0.000000,0.263852,-0.625000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
29,NaN,0.000000,-0.183150,0.132626,0.961538,0.000000,-0.547945,0.000000,-0.847458,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
30,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [25]:
#plotting flux over density(normalised) for different zones


rows = len(zone_names_array)
cols = len(zone_names_array[0])
fig, ax = plt.subplots(rows,cols, figsize = (30,20), sharey = True, sharex = True)
for i in range(rows):
    for j in range(cols):
        df_net.plot('time(s)', zone_names_array[i][j], ax = ax[i,j], linewidth = 0.5)
        ax[i,j].set_title(zone_names_array[i][j])
        ax[i,j].legend(['net flux'])
        ax[i,j].grid('on')

In [26]:
# Retrieve the background image
dh.fetch_background_image_from_path('ehv/background_images/EHV.Perron2.1_multisensor.png')
dh.bg

# Plot on top of the background image

fig = plt.figure(figsize=(20,8))
ax = fig.add_subplot(111)

xmin = -5134
ymin = -17731
xmax =  75135
ymax =  11645

# Plot of the background
ax.imshow(dh.bg, cmap = 'gray', extent=[xmin, xmax, ymin, ymax])

#Plot the boarding limits
for i in range(len(limits_array)):
    width = limits_array[i][1] - limits_array[i][0]
    height = limits_array[i][3] - limits_array[i][2]
    rect_limits = patches.Rectangle((limits_array[i][0], limits_array[i][2]), width, height, linewidth=3, edgecolor='r', facecolor='none')
    ax.add_patch(rect_limits)



# Plot starting and ending positions
# df_object_start_location.plot.scatter('x_pos', 'y_pos', s = 1, ax = ax)
# df_object_end_location.plot.scatter('x_pos', 'y_pos', s = 1, c = 'purple', ax = ax)

# ax.legend(['Boarding area 1', 'Boarding area 2', 'Start location', 'End location'])

trying to fetch: /storage/surfsara/ProRail_USE_LL_data/ehv/background_images/EHV.Perron2.1_multisensor.png
background fetched. Accessible as <this-object>.bg